 spring.application.name=backend

spring.datasource.url=jdbc:postgresql://ep-crimson-lake-at38r7vs-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_WmU7if9cvBNj

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}